### PR TITLE
New Mavlink, added simulator, video stabile +++

### PR DESCRIPTION
**Pull request by The1only**
This is a huge update that is not yet stable, just want to get it on the master to not get too far off as it is better than the current master.

### CODE REVIEW

**Comment by kikislater** [comment]
Simulator ! Really really nice, is there a how to or a doc ? 
Mind you open others to create issues on your fork ?

**Comment by The1only** [comment]
Ahh knew there was something missing, a manual... :-) 
I will write it this weekend. However what I suggest as a start;
1) Install QGC on a PC, and connect a joystick. 
2) Install the rosetta drone software on a phone
3) enable wlan tethering on it. Then connect the PC to the phone over wlan. 
4) connect a DJI drone hand controller using a USB cable and the Rosetta drone will start. 
4.1) If you got the Smart Controller, then install the Rosetta Drone there and do the same)
5) Hitt the SIM button, and then the Start button. 
6) Then open settings and enter the IP address to the PC.  
You should now get both video and telemetry too QGC. 
Then issue a TakeOff command from QGC (a button on the left side). 
The DJI Simulator will then takeoff and wait in the air. 
Now you can use your joystick to fly around. 
That proves you got started, now test the python script in the project using the dronekit, and you can start doing cool stuff...

**Comment by The1only** [comment]
PS: This is still work in progress so expect issues. I am improving it every day.

**Comment by The1only** [comment]
Please do create issues in my fork, and if you want to contribute you are all more than welcome. It is surprisingly mush work to implement the entire Mavlink protocol, especially as DJI does ting very different so one got to be creative.

**Comment by kikislater** [comment]
Cool ! I'll try when I have time. Issue are disabled in your fork

**Comment by The1only** [comment]
I know, I am unforking the code, as I am always merging to the wrong fork. Better start fresh. 
Will be ready in a bit...

**Pull request merged**
